name: Workflow for development

on:
  # Carry out builds on all push events (exclude production)
  push:
    branches:
    - 'develop'
  workflow_dispatch:

jobs:
  development-ci:
    name: Perform CI flow for development
    uses: ./.github/workflows/ci.yml
    with:
      target-env: development
    secrets: inherit
    
  create-release:
    needs: development-ci
    name: Tag Release
    uses: ./.github/workflows/release.yml
    with:
      target-env: development
    secrets: inherit
